[package]
name = "esp-viewer"
version = "0.1.0"
edition = "2024"

# Something has gotta reduce these binary sizes, fucking hell
[profile.release]
opt-level = "z"
lto = "thin"

[profile.release.package."*"]
opt-level = "z"

# Enable a tiny bit of optimization for your own code if needed, 
# or keep it at 0 for the fastest possible compile times.
[profile.dev]
opt-level = 1                # 0 for max compile speed, 1 if your game logic is CPU-heavy
debug = true
incremental = true           # Ensure incremental compilation is on
split-debuginfo = "unpacked" # Speeds up linking significantly on Windows/macOS

# Fully optimize all dependencies (including Bevy, wgpu, etc.)
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy_egui = "0.42.0"
bevy_panorbit_camera = "0.35.1"
base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wgpu-types = "29.0.4"
tes3 = { git = "https://github.com/nicholas477/tes3.git", features = [
    "bsa",
    "esp",
    "nif",
    "inspect",
] }
zip = "8.6.0"
toml = "1.1.5"
serde_toml = "0.0.1"
slotmap = "1.1.1"
arc-slice = "0.1.0"
async-trait = "0.1.92"
futures = { version = "0.3.34", features = ["alloc"] }

[dependencies.bevy]
version = "0.19.1"
default-features = false
features = [
    "2d",
    "ui",

    # Parts of Bevy:
    "bevy_asset",
    "bevy_log",
    "bevy_pbr",
    "bevy_core_pipeline",
    "bevy_gizmos",
    "bevy_dev_tools",
    "bevy_render",
    "bevy_window",
    "bevy_winit",
    "default_app",
    "default_platform",
    "picking",
    "scene",
    "3d_api",
    "bevy_anti_alias",
    "bevy_gizmos_render",
    "bevy_post_process",

    # Platform-Specific
    "webgl2", # Web: use WebGL2 instead of WebGPU

    # Asset File Format Support
    "bmp",
    "dds",
    "tga",
]

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
bevy = { version = "0.19.1", features = ["dynamic_linking"] }

# Desktop dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
directories = "6.0.0"
rfd = "0.17"
sevenz-rust2 = "0.22.2"

# WebAssembly-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
serde_urlencoded = "0.7"
wasm-bindgen = "0.2.128"
wasm-bindgen-futures = "0.4.77"
web-sys = { version = "0.3", features = [
    "Document",
    "Blob",
    "Event",
    "EventTarget",
    "File",
    "FileList",
    "FileSystemDirectoryHandle",
    "FileSystemHandle",
    "FileSystemFileHandle",
    "FileSystemGetFileOptions",
    "FileSystemGetDirectoryOptions",
    "FormData",
    "History",
    "HtmlDocument",
    "HtmlAnchorElement",
    "HtmlInputElement",
    "Location",
    "Response",
    "Request",
    "RequestInit",
    "Storage",
    "Url",
    "UrlSearchParams",
    "Window",
    "PermissionState",
    "IdbFactory",
    "IdbOpenDbRequest",
    "IdbDatabase",
    "IdbTransaction",
    "IdbObjectStore",
    "IdbRequest",
] }
js-sys = "0.3.104"
sevenz-rust2 = { version = "0.22.2", features = ["default_wasm"] }
