[package]
name = "esp-viewer"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 's'
lto = 'thin'

[dependencies]
bevy = {version = "0.19.1", features = ["bevy_dev_tools", "dds"]}
bevy_egui = "0.42.0"
bevy_panorbit_camera = "0.35.0"
js-sys = "0.3.104"
wasm-bindgen = "0.2.127"
wasm-bindgen-futures = "0.4.77"
wgpu-types = "29.0.4"
tes3 = { git = "https://github.com/Greatness7/tes3", features = ["esp", "nif"] }
zip = "8.6.0"

[dependencies.web-sys]
version = "0.3"
features = ["History", "Location", "Response", "Url", "UrlSearchParams", "Window"]
