[package]
name = "esp-viewer"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 's'
lto = 'thin'

[dependencies]
bevy_egui = "0.42.0"
bevy_panorbit_camera = { git = "https://github.com/nicholas477/bevy_panorbit_camera.git" }
base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wgpu-types = "29.0.4"
tes3 = { git = "https://github.com/Greatness7/tes3", features = ["esp", "nif"] }
zip = "8.6.0"
toml = "1.1.5"
serde_toml = "0.0.1"

[dependencies.bevy]
version = "0.19.1"
default-features = false
features = [
    "2d",
    "ui",

    # Parts of Bevy:
    "bevy_asset",
    "bevy_log",
    "bevy_pbr",
    "bevy_core_pipeline",
    "bevy_gizmos",
    "bevy_dev_tools",
    "bevy_render",
    "bevy_window",
    "bevy_winit",
    "default_app",
    "default_platform",
    "picking",
    "scene",
    "3d_api",
    "bevy_anti_alias",
    "bevy_gizmos_render",
    "bevy_post_process",

    # Platform-Specific
    "webgl2", # Web: use WebGL2 instead of WebGPU

    # Asset File Format Support
    "bmp",
    "dds",
    "tga",
]

# Desktop dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
directories = "6.0.0"
rfd = "0.17"

# WebAssembly-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
serde_urlencoded = "0.7"
wasm-bindgen = "0.2.128"
wasm-bindgen-futures = "0.4.77"
web-sys = { version = "0.3", features = [
    "Document",
    "Event",
    "EventTarget",
    "File",
    "FileList",
    "FormData",
    "History",
    "HtmlDocument",
    "HtmlInputElement",
    "Location",
    "Response",
    "Request",
    "RequestInit",
    "Url",
    "UrlSearchParams",
    "Window",
] }
js-sys = "0.3.104"
